<?xml version="1.0"?>
<!DOCTYPE feature_key_file [
   <!ELEMENT feature_key_file (comments, feature+)>
   <!ELEMENT comments (#PCDATA)>
   <!ELEMENT feature (name, description?, is_sequential, parallel_dimensions)>
   <!ELEMENT name (#PCDATA)>
   <!ELEMENT description (#PCDATA)>
   <!ELEMENT is_sequential (#PCDATA)>
   <!ELEMENT parallel_dimensions (#PCDATA)>
]>

<feature_key_file>

   <comments></comments>

   <feature>
      <name>Range</name>
      <description>Difference in semitones between the highest and lowest pitches.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
   </feature>

   <feature>
      <name>Mean Pitch</name>
      <description>Mean MIDI pitch value, averaged across all pitched notes in the piece. Set to 0 if there are no pitched notes.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
   </feature>

   <feature>
      <name>Pitch Variability</name>
      <description>Standard deviation of the MIDI pitches of all pitched notes in the piece. Provides a measure of how close the pitches as a whole are to the mean pitch.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
   </feature>

   <feature>
      <name>Major or Minor</name>
      <description>Whether the piece is major or minor, as indicated by the first encountered major/minor metadata tag in the piece. Set to 0 if the metadata indicates that the piece is major, or set to 1 if the metadata indicates that it is minor. Defaults to 0 if the key signature is unknown.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
   </feature>

</feature_key_file>